### ISSUE TITLE
Bug: Permission denied for adding new quote

### ISSUE THREAD

**Issue by firefighterduck** [TheMC47/random-quote#5]
**Describe the bug**
I followed the "add more quotes" guide and now I can't push the new quote and get a permission denied error. Pulling works.

**To Reproduce**
Try to push with a Github account that is not the same as the maintainer's. 
Use SSH for this.

**Expected behavior**
Pushing should be allowed for other contributors.

**Desktop (please complete the following information):**
 - Windows 10
 - Git for Windows 2.28 / WSL Git 2.25.1

**Additional context**
Error output:
```
ERROR: Permission to TheMC47/random-quote.git denied to firefighterduck.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Git remote configuration:
```
origin  git@github.com:TheMC47/random-quote.git (fetch)
origin  git@github.com:TheMC47/random-quote.git (push)
```

**Comment by TheMC47** [comment]
Thank you for the bug report! I'll update the instructions to fork the repository instead of pushing to the same branch

**Comment by TheMC47** [comment]
@firefighterduck  can you please follow the updated instructions and report back?
